language: rust
rust:
  - nightly
before_install:
  - rustup target add wasm32-unknown-unknown
  - cargo install --git https://github.com/paritytech/wasm-utils wasm-build
env:
- TUTOR_DIR=step-0
- TUTOR_DIR=step-1
- TUTOR_DIR=step-2
- TUTOR_DIR=step-3
- TUTOR_DIR=step-4
- TUTOR_DIR=step-5
script:
  - cd $TUTOR_DIR
  - cargo build --release --target wasm32-unknown-unknown
  - wasm-build --target=wasm32-unknown-unknown ./target pwasm_tutorial_contract
